### PR TITLE
Fix support for BigFloat u0

### LINKED ISSUE #43: BigFloat support for TwoPointBVProblem using MIRK4
Using BigFloat with a TwoPointBVProblem and MIRK4 solver currently fails with the following error:

> ArgumentError: matrix type SparseArrays.SparseMatrixCSC{BigFloat,Int64}not supported. Try lu(convert(SparseMatrixCSC{Float64/ComplexF64,Int}, A)) for sparse floating point LU using UMFPACK or lu(Array(A)) for generic dense LU.

### PR DESCRIPTION
**Pull request by ErikQQY**
Fix #43
Unblock #178 
Possibly need https://github.com/SciML/PreallocationTools.jl/issues/72

I think ```get_tmp``` in PreallocationTools.jl doesn't support BigFloat and would cause ```cannot reinterpret `BigFloat` as `ForwardDiff.Dual`, type `ForwardDiff.Dual` is not a bits type``` error, similar issue is https://github.com/SciML/PreallocationTools.jl/issues/72

@avik-pal 
<details>

<summary>Full stacktrace</summary>

```julia
ERROR: ArgumentError: cannot reinterpret `BigFloat` as `ForwardDiff.Dual{ForwardDiff.Tag{BoundaryValueDiffEq.__Fix3{BoundaryValueDiffEq.var"#131#137"{SciMLBase.StandardBVProblem, BoundaryValueDiffEq.MIRKCache{true, BigFloat, Tuple{Int64}, BVPFunction{true, SciMLBase.FullSpecialize, false, typeof(simplependulum!), typeof(bc!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, SymbolicIndexingInterface.SymbolCache{Nothing, Nothing, Nothing, Nothing, Dict{Any, Any}}}, typeof(bc!), BVProblem{Vector{BigFloat}, Tuple{Float64, Float64}, true, Nothing, SciMLBase.NullParameters, BVPFunction{true, SciMLBase.FullSpecialize, false, typeof(simplependulum!), typeof(bc!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, SymbolicIndexingInterface.SymbolCache{Nothing, Nothing, Nothing, Nothing, Dict{Any, Any}}}, SciMLBase.StandardBVProblem, Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}}}, SciMLBase.StandardBVProblem, SciMLBase.NullParameters, MIRK4{Nothing, BVPJacobianAlgorithm{AutoForwardDiff{nothing, Nothing}, AutoSparse{AutoForwardDiff{nothing, Nothing}, ADTypes.NoSparsityDetector, ADTypes.NoColoringAlgorithm}, AutoSparse{AutoForwardDiff{nothing, Nothing}, ADTypes.NoSparsityDetector, ADTypes.NoColoringAlgorithm}}, Float64}, BoundaryValueDiffEq.MIRKTableau{Int64, Vector{BigFloat}, Vector{BigFloat}, Vector{BigFloat}, Matrix{BigFloat}}, BoundaryValueDiffEq.MIRKInterpTableau{Int64, Vector{BigFloat}, Vector{BigFloat}, Vector{BigFloat}, BigFloat}, Vector{BigFloat}, Vector{Float64}, Vector{Float64}, Vector{PreallocationTools.DiffCache{Matrix{BigFloat}, Vector{BigFloat}}}, Vector{Matrix{BigFloat}}, Vector{PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}}, Vector{Vector{BigFloat}}, Vector{PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}}, PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}, Vector{BigFloat}, Vector{Vector{BigFloat}}, Vector{Vector{BigFloat}}, Tuple{Int64}, @NamedTuple{abstol::Float64, dt::Float64, adaptive::Bool}}}, SciMLBase.NullParameters}, BigFloat}, BigFloat, 11}`, type `ForwardDiff.Dual{ForwardDiff.Tag{BoundaryValueDiffEq.__Fix3{BoundaryValueDiffEq.var"#131#137"{SciMLBase.StandardBVProblem, BoundaryValueDiffEq.MIRKCache{true, BigFloat, Tuple{Int64}, BVPFunction{true, SciMLBase.FullSpecialize, false, typeof(simplependulum!), typeof(bc!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, SymbolicIndexingInterface.SymbolCache{Nothing, Nothing, Nothing, Nothing, Dict{Any, Any}}}, typeof(bc!), BVProblem{Vector{BigFloat}, Tuple{Float64, Float64}, true, Nothing, SciMLBase.NullParameters, BVPFunction{true, SciMLBase.FullSpecialize, false, typeof(simplependulum!), typeof(bc!), LinearAlgebra.UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing, Nothing, SymbolicIndexingInterface.SymbolCache{Nothing, Nothing, Nothing, Nothing, Dict{Any, Any}}}, SciMLBase.StandardBVProblem, Base.Pairs{Symbol, Union{}, Tuple{}, @NamedTuple{}}}, SciMLBase.StandardBVProblem, SciMLBase.NullParameters, MIRK4{Nothing, BVPJacobianAlgorithm{AutoForwardDiff{nothing, Nothing}, AutoSparse{AutoForwardDiff{nothing, Nothing}, ADTypes.NoSparsityDetector, ADTypes.NoColoringAlgorithm}, AutoSparse{AutoForwardDiff{nothing, Nothing}, ADTypes.NoSparsityDetector, ADTypes.NoColoringAlgorithm}}, Float64}, BoundaryValueDiffEq.MIRKTableau{Int64, Vector{BigFloat}, Vector{BigFloat}, Vector{BigFloat}, Matrix{BigFloat}}, BoundaryValueDiffEq.MIRKInterpTableau{Int64, Vector{BigFloat}, Vector{BigFloat}, Vector{BigFloat}, BigFloat}, Vector{BigFloat}, Vector{Float64}, Vector{Float64}, Vector{PreallocationTools.DiffCache{Matrix{BigFloat}, Vector{BigFloat}}}, Vector{Matrix{BigFloat}}, Vector{PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}}, Vector{Vector{BigFloat}}, Vector{PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}}, PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}, Vector{BigFloat}, Vector{Vector{BigFloat}}, Vector{Vector{BigFloat}}, Tuple{Int64}, @NamedTuple{abstol::Float64, dt::Float64, adaptive::Bool}}}, SciMLBase.NullParameters}, BigFloat}, BigFloat, 11}` is not a bits type
Stacktrace:
  [1] (::Base.var"#throwbits#333")(S::Type, T::Type, U::Type)
    @ Base .\reinterpretarray.jl:16
  [2] reinterpret(::Type{ForwardDiff.Dual{ForwardDiff.Tag{…}, BigFloat, 11}}, a::SubArray{BigFloat, 1, Vector{BigFloat}, Tuple{UnitRange{…}}, true})
    @ Base .\reinterpretarray.jl:62
  [3] get_tmp(dc::PreallocationTools.DiffCache{Vector{BigFloat}, Vector{BigFloat}}, u::Vector{ForwardDiff.Dual{ForwardDiff.Tag{…}, BigFloat, 11}})
    @ PreallocationTools D:\Julia\.julia\packages\PreallocationTools\vWjVk\src\PreallocationTools.jl:152
  [4] (::BoundaryValueDiffEq.var"#3#4"{PreallocationTools.DiffCache{Vector{…}, Vector{…}}, Vector{ForwardDiff.Dual{…}}})()
    @ BoundaryValueDiffEq D:\SciML\BVP\bc\BoundaryValueDiffEq.jl\src\types.jl:169
  [5] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging .\logging.jl:515
  [6] with_logger(f::Function, logger::Base.CoreLogging.NullLogger)
    @ Base.CoreLogging .\logging.jl:627
  [7] get_tmp
    @ D:\SciML\BVP\bc\BoundaryValueDiffEq.jl\src\types.jl:168 [inlined]
  [8] _broadcast_getindex_evalf
    @ .\broadcast.jl:709 [inlined]
  [9] _broadcast_getindex
    @ .\broadcast.jl:682 [inlined]
 [10] getindex
    @ .\broadcast.jl:636 [inlined]
 [11] copy
    @ .\broadcast.jl:942 [inlined]
 [12] materialize
    @ .\broadcast.jl:903 [inlined]
```

</details>

### CODE REVIEW

File: src/utils.jl [hunk 1]
```diff
@@ -185,12 +185,31 @@ function __get_bcresid_prototype(::StandardBVProblem, prob::BVProblem, u)
...
+@inline function __fill_like(v, x)
+    y = __similar(x)
     fill!(y, v)
     return y
 end
-@inline __zeros_like(args...) = __fill_like(0, args...)
+@inline function __zeros_like(u)
+    if ArrayInterface.can_setindex(u)
+        eltype(u) <: BigFloat && __fill_like(BigFloat(0), u)
+        return u
```
Comment (avik-pal) [inline src/utils.jl:209]: missing a `u .= 0`?

Comment (ErikQQY) [reply src/utils.jl:209]: There is a `return __fill_like(0, u)` below

Comment (ErikQQY) [reply src/utils.jl:209]: There is a `return __fill_like(0, u)` below

**Comment by ChrisRackauckas** [comment]
`__similar(x)`, why are we not just using `zero(x)`?

**Comment by ChrisRackauckas** [comment]
> I think get_tmp in PreallocationTools.jl doesn't support BigFloat and would cause cannot reinterpret `BigFloat` as `ForwardDiff.Dual`, type `ForwardDiff.Dual` is not a bits type error, similar issue is https://github.com/SciML/PreallocationTools.jl/issues/72

We should just use a LazyBufferCache then?

**Comment by ErikQQY** [comment]
Implemented a special diff cache for the BigFloat case, which may not be the best solution, and some improvement is still necessary, the BigFloat support for MIRK is working now!!

**Comment by ChrisRackauckas** [comment]
I don't understand the need for `__init_bigfloat_array!!`: aren't you always building BigFloat caches now even if you don't use BigFloats? Why isn't this a part of the DualCache? Can't you just use the Vector{Any} in the dualcache?

File: src/types.jl [hunk 2]
```diff
@@ -152,13 +152,54 @@ end
...
+BigFloatDiffCache(u::AbstractArray, ::Val{N}; levels::Int = 1) where {N} = BigFloatDiffCache(u, N; levels)
+
+function get_tmp(dc::BigFloatDiffCache, u::T) where {T <: ForwardDiff.Dual}
+    nelem = length(dc.du)
+    PreallocationTools._restructure(dc.du, view(T.(dc.dual_du), 1:nelem))
+end
+function get_tmp(dc::BigFloatDiffCache, u::AbstractArray{T}) where {T <: ForwardDiff.Dual}
+    nelem = length(dc.du)
+    PreallocationTools._restructure(dc.du, view(T.(dc.dual_du), 1:nelem))
+end
```
Comment (ChrisRackauckas) [inline src/types.jl:185]: Don't you just need to specialize that if it's not a bitstype then you don't reinterpret? Just fix PreallocationTools.jl here?

Comment (ChrisRackauckas) [reply src/types.jl:185]: I can make the PR

Comment (ErikQQY) [reply src/types.jl:185]: > Don't you just need to specialize that if it's not a bitstype then you don't reinterpret? Just fix PreallocationTools.jl here?

Yeah, I will just specialize here.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/PreallocationTools.jl/pull/112 should be all you need?

**Comment by ChrisRackauckas** [comment]
Hopefully this can close 🤞 and BVP needs to do nothing special.

File: src/solve/mirk.jl [hunk 3]
```diff
@@ -42,10 +42,10 @@ function SciMLBase.__init(prob::BVProblem, alg::AbstractMIRK; dt = 0.0,
     mesh_dt = diff(mesh)
 
     chunksize = pickchunksize(N * (Nig - 1))
-    __alloc = @closure x -> __maybe_allocate_diffcache(vec(x), chunksize, alg.jac_alg)
+    __alloc = @closure x -> __maybe_allocate_diffcache(vec(__similar(x)), chunksize, alg.jac_alg)
 
-    fᵢ_cache = __alloc(similar(X))
-    fᵢ₂_cache = vec(similar(X))
+    fᵢ_cache = __alloc(__similar(X))
+    fᵢ₂_cache = vec(__similar(X))
```
Comment (ChrisRackauckas) [inline src/solve/mirk.jl:48]:
```suggestion
    fᵢ_cache = __alloc(zero(X))
    fᵢ₂_cache = vec(zero(X))
```

Why not just use `zero` everywhere?

Comment (ErikQQY) [reply src/solve/mirk.jl]: Yeah, changed to `zero` everywhere

File: src/types.jl [hunk 4]
```diff
@@ -155,8 +155,8 @@ end
 function __maybe_allocate_diffcache(x, chunksize, jac_alg)
     return __needs_diffcache(jac_alg) ? DiffCache(x, chunksize) : FakeDiffCache(x)
 end
-__maybe_allocate_diffcache(x::DiffCache, chunksize) = DiffCache(similar(x.du), chunksize)
-__maybe_allocate_diffcache(x::FakeDiffCache, _) = FakeDiffCache(similar(x.du))
+__maybe_allocate_diffcache(x::DiffCache, chunksize) = DiffCache(__similar(x.du), chunksize)
+__maybe_allocate_diffcache(x::FakeDiffCache, _) = FakeDiffCache(__similar(x.du))
```
Comment (ChrisRackauckas) [inline src/types.jl:159]:
```suggestion
__maybe_allocate_diffcache(x::DiffCache, chunksize) = DiffCache(zero(x.du), chunksize)
__maybe_allocate_diffcache(x::FakeDiffCache, _) = FakeDiffCache(zero(x.du))
```

File: src/utils.jl [hunk 5]
```diff
@@ -112,7 +112,7 @@ function __append_similar!(x::AbstractVector{<:AbstractArray}, n, _)
     N = n - length(x)
     N == 0 && return x
     N < 0 && throw(ArgumentError("Cannot append a negative number of elements"))
-    append!(x, [similar(last(x)) for _ in 1:N])
+    append!(x, [__similar(last(x)) for _ in 1:N])
```
Comment (ChrisRackauckas) [inline src/utils.jl:115]:
```suggestion
    append!(x, [zero(last(x)) for _ in 1:N])
```

File: src/utils.jl [hunk 6]
```diff
@@ -195,12 +195,24 @@ function __get_bcresid_prototype(::StandardBVProblem, prob::BVProblem, u)
     return prototype, size(prototype)
 end
 
-@inline function __fill_like(v, x, args...)
+@inline function __similar(x, args...)
     y = similar(x, args...)
+    eltype(y) <: BigFloat && fill!(y, BigFloat(0))
```
Comment (ChrisRackauckas) [inline src/utils.jl:200]: is there a reason to not always fill with zeros?

Comment (ErikQQY) [reply src/utils.jl]: zeros is better, just change them all. While NonlinearSolve is doing the similar thing like specialize on bigfloat and do `__similar` things in https://github.com/SciML/NonlinearSolve.jl/pull/438, maybe we can change to zeros everywhere in NonlinearSolve.jl as well?

Comment (ChrisRackauckas) [reply src/utils.jl]: We should. https://github.com/SciML/SciMLStyle?tab=readme-ov-file#always-default-to-constructs-which-initialize-data

Comment (ChrisRackauckas) [reply src/utils.jl]: Note this will also fix issues with non-fully defined functions. For example, if a user doesn't write to `du[i]`, we should still converge now, while before you'd get something random. So a few bugs should be fixed, some bugs avoided, etc. Avoiding uninitialized memory is just a good idea all around and NonlinearSolve needs to do this change too.
